require 'spec_helper'
require 'json'

# Unit tests for WorkflowMaxRuby::TaskApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaskApi' do
  before do
    # run before each test
    @api_instance = WorkflowMaxRuby::TaskApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Task' do
    it 'should create an instance of TaskApi' do
      expect(@api_instance).to be_instance_of(WorkflowMaxRuby::TaskApi)
    end
  end


end
