=begin
#Clients API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.3
Contact: blair@hireassemble.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WorkflowMaxRuby::Clients
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Contacts' do
  before do
    # run before each test
    @instance = WorkflowMaxRuby::Clients::Contacts.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Contacts' do
    it 'should create an instance of Contacts' do
      expect(@instance).to be_instance_of(WorkflowMaxRuby::Clients::Contacts)
    end
  end

  describe 'test attribute "contacts"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
