require 'spec_helper'
require 'json'

# Unit tests for WorkflowMaxRuby::StaffApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StaffApi' do
  before do
    # run before each test
    @api_instance = WorkflowMaxRuby::StaffApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Staff' do
    it 'should create an instance of StaffApi' do
      expect(@api_instance).to be_instance_of(WorkflowMaxRuby::StaffApi)
    end
  end

end
