=begin
#Xero Projects API

#This is the Xero Projects API

Contact: api@xero.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'time'
require 'date'

module WorkflowMaxRuby::Clients
  require 'bigdecimal'

  class Client
    attr_accessor :uuid
    attr_accessor :name
    attr_accessor :title
    attr_accessor :gender
    attr_accessor :first_name
    attr_accessor :last_name
    attr_accessor :other_name
    attr_accessor :email
    attr_accessor :date_of_birth
    attr_accessor :address
    attr_accessor :city
    attr_accessor :region
    attr_accessor :post_code
    attr_accessor :country
    attr_accessor :postal_address
    attr_accessor :postal_city
    attr_accessor :postal_region
    attr_accessor :postal_post_code
    attr_accessor :postal_country
    attr_accessor :phone
    attr_accessor :fax
    attr_accessor :website
    attr_accessor :referral_source
    attr_accessor :export_code
    attr_accessor :is_prospect
    attr_accessor :is_archived
    attr_accessor :is_deleted
    attr_accessor :account_manager
    attr_accessor :type
    attr_accessor :contacts


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'name' => :'name',
        :'title' => :'title',
        :'gender' => :'gender',
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'other_name' => :'other_name',
        :'email' => :'email',
        :'date_of_birth' => :'date_of_birth',
        :'address' => :'address',
        :'city' => :'city',
        :'region' => :'region',
        :'post_code' => :'post_code',
        :'country' => :'country',
        :'postal_address' => :'postal_address',
        :'postal_city' => :'postal_city',
        :'postal_region' => :'postal_region',
        :'postal_post_code' => :'postal_post_code',
        :'phone' => :'phone',
        :'fax' => :'fax',
        :'website' => :'website',
        :'referral_source' => :'referral_source',
        :'export_code' => :'export_code',
        :'is_prospect' => :'is_prospect',
        :'is_archived' => :'is_archived',
        :'is_deleted' => :'is_deleted',
        :'account_manager' => :'account_manager',
        :'type' => :'type',
        :'contacts' => :'contacts'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'name' => :'String',
        :'title' => :'String',
        :'gender' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'other_name' => :'String',
        :'email' => :'String',
        :'date_of_birth' => :'DateTime',
        :'address' => :'String',
        :'city' => :'String',
        :'region' => :'String',
        :'post_code' => :'String',
        :'country' => :'String',
        :'postal_address' => :'String',
        :'postal_city' => :'String',
        :'postal_region' => :'String',
        :'postal_post_code' => :'String',
        :'phone' => :'String',
        :'fax' => :'String',
        :'website' => :'String',
        :'referral_source' => :'String',
        :'export_code' => :'String',
        :'is_prospect' => :'Boolean',
        :'is_archived' => :'Boolean',
        :'is_deleted' => :'Boolean',
        :'account_manager' => :'AccountManager',
        :'type' => :'Type',
        :'contacts' => :'Contacts',
        :'billing_contact' => :'BillingContact'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WorkflowMaxRuby::Clients::Client` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WorkflowMaxRuby::Clients::Client`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'other_name')
        self.other_name = attributes[:'other_name']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'date_of_birth')
        self.date_of_birth = attributes[:'date_of_birth']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end

      if attributes.key?(:'post_code')
        self.post_code = attributes[:'post_code']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'postal_address')
        self.postal_address = attributes[:'postal_address']
      end

      if attributes.key?(:'postal_city')
        self.postal_city = attributes[:'postal_city']
      end

      if attributes.key?(:'postal_region')
        self.postal_region = attributes[:'postal_region']
      end

      if attributes.key?(:'postal_post_code')
        self.postal_post_code = attributes[:'postal_post_code']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'fax')
        self.fax = attributes[:'fax']
      end

      if attributes.key?(:'website')
        self.website = attributes[:'website']
      end

      if attributes.key?(:'referral_source')
        self.referral_source = attributes[:'v']
      end

      if attributes.key?(:'export_code')
        self.export_code = attributes[:'export_code']
      end

      if attributes.key?(:'is_prospect')
        self.is_prospect = attributes[:'is_prospect']
      end

      if attributes.key?(:'is_archived')
        self.is_archived = attributes[:'is_archived']
      end

      if attributes.key?(:'is_deleted')
        self.is_deleted = attributes[:'is_deleted']
      end

      if attributes.key?(:'account_manager')
        self.account_manager = attributes[:'account_manager']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'contacts')
        self.contacts = attributes[:'contacts']
      end

      if attributes.key?(:'billing_client')
        self.billing_client = attributes[:'billing_client']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
        uuid == o.uuid &&
        name == o.name &&
        title == o.title &&
        gender == o.gender &&
        first_name == o.first_name &&
        last_name == o.last_name &&
        other_name == o.other_name &&
        email == o.email &&
        date_of_birth == o.date_of_birth &&
        address == o.address &&
        city == o.city &&
        region == o.region &&
        post_code == o.post_code &&
        country == o.country &&
        postal_address == o.postal_address &&
        postal_city == o.postal_city &&
        postal_region == o.postal_region &&
        postal_post_code == o.postal_post_code &&
        phone == o.phone &&
        fax == o.fax &&
        website == o.website &&
        referral_source == o.referral_source &&
        export_code == o.export_code &&
        is_prospect == o.is_prospect &&
        is_archived == o.is_archived &&
        is_deleted == o.is_deleted &&
        account_manager == o.account_manager &&
        type == o.type &&
        contacts == o.contacts &&
        billing_client == o.billing_client
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, name, title, gender, first_name, last_name, other_name, email, date_of_birth, address, city, region, post_code, country, postal_address, postal_city, postal_region, postal_post_code, phone, fax, website, referral_source, export_code, is_prospect, is_archived, is_deleted, account_manager, type, contacts, billing_client].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(parse_date(value))
      when :Date
        Date.parse(parse_date(value))
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BigDecimal
        BigDecimal(value.to_s)
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        WorkflowMaxRuby::Clients::Client.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash(downcase: false)
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        key = downcase ? attr : param
        hash[key] = _to_hash(value, downcase: downcase)
      end
      hash
    end

    # Returns the object in the form of hash with snake_case
    def to_attributes
      to_hash(downcase: true)
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value, downcase: false)
      if value.is_a?(Array)
        value.map do |v|
          v.to_hash(downcase: downcase)
        end
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.map { |k, v| hash[k] = _to_hash(v, downcase: downcase) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash(downcase: downcase)
      else
        value
      end
    end

    def parse_date(datestring)
      if datestring.include?('Date')
        date_pattern = /\/Date\((-?\d+)(\+\d+)?\)\//
        original, date, timezone = *date_pattern.match(datestring)
        date = (date.to_i / 1000)
        Time.at(date).utc.strftime('%Y-%m-%dT%H:%M:%S%z').to_s
      else # handle date 'types' for small subset of payroll API's
        Time.parse(datestring).strftime('%Y-%m-%dT%H:%M:%S').to_s
      end
    end
  end
end
