=begin
#Times API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.1.3
Contact: blair@hireassemble.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WorkflowMaxRuby::Invoices::Invoice
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WFMTime' do
  before do
    # run before each test
    @instance = WorkflowMaxRuby::Times::WFMTime.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WFMTime' do
    it 'should create an instance of WFMTime' do
      expect(@instance).to be_instance_of(WorkflowMaxRuby::Times::WFMTime)
    end
  end

end
