=begin
#WorkflowMax API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

Contact: blair@hireassemble.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

The version of the XeroOpenAPI document: 2.12.0
=end

module WorkflowMaxRuby
  VERSION = '1.0.15'
end
