require 'spec_helper'
require 'json'

# Unit tests for WorkflowMaxRuby::TimeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimeApi' do
  before do
    # run before each test
    @api_instance = WorkflowMaxRuby::TimeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Time' do
    it 'should create an instance of TimeApi' do
      expect(@api_instance).to be_instance_of(WorkflowMaxRuby::TimeApi)
    end
  end

end
