require 'spec_helper'
require 'json'

# Unit tests for WorkflowMaxRuby::InvoiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvoiceApi' do
  before do
    # run before each test
    @api_instance = WorkflowMaxRuby::InvoiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Invoice' do
    it 'should create an instance of InvoiceApi' do
      expect(@api_instance).to be_instance_of(WorkflowMaxRuby::InvoiceApi)
    end
  end


end
