require 'spec_helper'
require 'json'

# Unit tests for WorkflowMaxRuby::ClientApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClientApi' do
  before do
    # run before each test
    @api_instance = WorkflowMaxRuby::ClientApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Client' do
    it 'should create an instance of ClientApi' do
      expect(@api_instance).to be_instance_of(WorkflowMaxRuby::ClientApi)
    end
  end


end
