require 'spec_helper'
require 'json'

# Unit tests for WorkflowMaxRuby::SupplierApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SupplierApi' do
  before do
    # run before each test
    @api_instance = WorkflowMaxRuby::SupplierApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Supplier' do
    it 'should create an instance of SupplierApi' do
      expect(@api_instance).to be_instance_of(WorkflowMaxRuby::SupplierApi)
    end
  end

end
